title: Đúc Kết
description: Ghi chép và đúc kết từ những gì đọc được, học được.
lang: vi

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
